
####################################################################################
# Generated by Vivado 2023.1 built on 'Sun May  7 15:04:56 MDT 2023' by 'xbuild'
# Command Used: write_xdc finn_design.xdc
####################################################################################


# Vivado Generated miscellaneous constraints 

#revert back to original instance
current_instance -quiet
